crash
client:
*** glibc detected ***
/home/arton/zillians/build/bin/compiler/bin/ts-vm: double free or
corruption (!prev): 0x00002ad0d2af5310 ***

server:
TCPSession ctor, this = 0x6f75140
client arton is added
add player
error while reading sequence message: End of file
terminate called after throwing an instance of
'boost::system::system_error'
  what():  write: Broken pipe
  Aborted
  Error: virtual machine failed to run on entry 'server_entry'
  make: *** [s] Error 255